import type { BB84SimulationResponse, CapabilitiesResponse } from '../types/api'

export const capabilitiesFixture: CapabilitiesResponse = {
  version: '0.1.0',
  profiles: [
    {
      id: 'QKD-ASSUMED',
      name: 'QKD-ASSUMED',
      family: 'qkd',
      implemented: true,
      status: 'current',
      description: 'BB84 with assumed classical authentication.',
      establishment: ['BB84'],
      authentication: ['QKD classical authentication: assumed'],
      algorithms: ['BB84'],
      hybrid: false,
      diversified: false,
      supports_qkd: true,
      supports_data_plane: false,
    },
    {
      id: 'PQC-BASE',
      name: 'PQC-BASE',
      family: 'pqc',
      implemented: true,
      status: 'current',
      description: 'ML-KEM-768 with ML-DSA-65.',
      establishment: ['ML-KEM-768'],
      authentication: ['PQC mutual authentication: ML-DSA-65'],
      algorithms: ['ML-KEM-768', 'ML-DSA-65', 'HKDF-SHA-384', 'HMAC-SHA-384'],
      hybrid: false,
      diversified: false,
      supports_qkd: false,
      supports_data_plane: true,
    },
  ],
  protocols: [
    { id: 'bb84', name: 'BB84', implemented: true, description: 'Available' },
    { id: 'e91', name: 'E91', implemented: false, description: 'Planned' },
  ],
  channels: [
    {
      id: 'depolarizing',
      name: 'Depolarizing',
      implemented: true,
      description: 'Noise',
      parameters: [
        {
          key: 'p',
          label: 'Noise probability',
          symbol: 'p',
          minimum: 0,
          maximum: 1,
          step: 0.01,
          default: 0.03,
          description: 'Strength',
        },
      ],
    },
  ],
  adversaries: [
    {
      id: 'intercept_resend',
      name: 'Eve: intercept-resend',
      implemented: true,
      description: 'Seeded adversary stage',
      parameters: [
        {
          key: 'intercept_fraction',
          label: 'Intercept fraction',
          symbol: 'f',
          minimum: 0,
          maximum: 1,
          step: 0.01,
          default: 1,
          description: 'Interception probability',
        },
      ],
    },
  ],
  features: [],
  limits: { max_signals: 100_000, max_channels: 12, inspector_records: 64 },
}

export const resultFixture: BB84SimulationResponse = {
  metadata: {
    request_id: 'e62dd185-107b-4e9f-9f09-a2f28e02babc',
    protocol: 'bb84',
    seed: 2026,
    duration_ms: 18.42,
    inspector_limit: 64,
    inspector_truncated: false,
  },
  channels: [],
  attack_diagnostics: [],
  metrics: {
    n_raw: 64,
    n_sifted: 32,
    sifting_efficiency: 0.5,
    qber: 0,
    qber_z: 0,
    qber_x: 0,
    qber_aggregated: 0,
  },
  postprocessing: {
    status: 'completed',
    abort_reason: null,
    n_disclosed: 7,
    estimated_qber: 0,
    estimated_qber_z: 0,
    estimated_qber_x: 0,
    estimated_qber_aggregated: 0,
    phase_error_bound: 0,
    n_candidate: 25,
    leak_ec: 4,
    corrected_errors: 0,
    verification_passed: true,
    verification_leakage: 8,
    n_reconciled: 25,
    n_final: 13,
    compression_ratio: 0.52,
    final_secret_fraction: 0.203125,
  },
  alice_basis_counts: { Z: 2, X: 2 },
  bob_basis_counts: { Z: 2, X: 2 },
  bob_outcome_counts: { zero: 3, one: 1 },
  transmissions: [
    {
      index: 0,
      alice_bit: 0,
      alice_basis: 'Z',
      bob_basis: 'Z',
      bob_result: 0,
      basis_match: true,
      sifted_error: false,
    },
  ],
}
